apiVersion: skaffold/v4beta5
kind: Config
manifests:
  rawYaml:
    - ./infra/k8s/*
build:
  local:
    push: false # Evita pushear a dockerhub por defecto
  artifacts:
    - image: cesca2092/client
      context: "../client"
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: "src/**/*.js"
    - image: cesca2092/comments
      context: "comments"
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: "*.js"
    - image: cesca2092/event-bus
      context: "event-bus"
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: "*.js"
    - image: cesca2092/moderation
      context: "moderation"
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: "*.js"
    - image: cesca2092/posts
      context: "posts"
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: "*.js"
    - image: cesca2092/query
      context: "query"
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: "*.js"
