apiVersion: apps/v1
kind: Deployment
metadata:
  name: comments-depl
spec: #como debe comportarse
  replicas: 1 # indica el numero de pods que se quieren crear corriendo una imagen
  selector:
    matchLabels:
      app: comments # buscar todos los pods creados con el nombre comments
  template: # especifica la configuracion exacta del pod que el deployment hara
    metadata:
      labels:
        app: comments
    spec:
      containers:
        - name: comments
          image: cesca2092/comments # si se deja asi es como si estuviera como latest
---
apiVersion: v1
kind: Service
metadata:
  name: comments-srv
spec:
  # type: NodePort  - Por defecto es ClusterIp
  selector:
    app: comments # find all pods named comments and expose them
  ports:
    - name: comments
      protocol: TCP
      port: 4001 # Nodeport
      targetPort: 4001 # Port from application
